### ISSUE TITLE
Links are not visible anymore

### ISSUE THREAD

**Issue by jobe001** [Gileba-org/mod_tablemakerforcsv#69]
If you will insert a link (html-code) in a cell, this will not be visible in releases later then v. 3.0.0
Example attached.
[Muster.csv](https://github.com/Gileba-org/mod_tablemakerforcsv/files/11044911/Muster.csv)

**Comment by jobe001** [comment]
Thanks!
I think a option was a good idea.

**Comment by jobe001** [comment]
Hello Gijs,

 

first – thanks for the option.

But I have a problem with the syntax of the tags.

If I use [<a>     ] and I click safe – the tag would be removed by joomla. If I use only [a    ] it don‘t  work.

 

BR

Johann

 

Von: Gijs Lamon ***@***.***> 
Gesendet: Montag, 24. April 2023 18:40
An: Gileba-org/mod_tablemakerforcsv ***@***.***>
Cc: jobe001 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Gileba-org/mod_tablemakerforcsv] Links are not visible anymore (Issue #69)

 

Closed #69 <https://github.com/Gileba-org/mod_tablemakerforcsv/issues/69>  as completed.

**Comment by Gileba** [comment]
Hi Johann,

You should only add "a" (without the quotation marks) to the list of allowed tags. However, I found out that attributes are still filtered. I'm working on a solution on it. When it's ready (version 3.4.1), you'll see an extra field "Allowed attributes" where you can enter "href" (again, without the quotation marks) to be allowed.

**Comment by jobe001** [comment]
Thanks soooooo much!!

 

Von: Gijs Lamon ***@***.***> 
Gesendet: Freitag, 28. April 2023 20:25
An: Gileba-org/mod_tablemakerforcsv ***@***.***>
Cc: jobe001 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Gileba-org/mod_tablemakerforcsv] Links are not visible anymore (Issue #69)

 

Hi Johann,

You should only add "a" (without the quotation marks) to the list of allowed tags. However, I found out that attributes are still filtered. I'm working on a solution on it. When it's ready (version 3.4.1), you'll see an extra field "Allowed attributes" where you can enter "href" (again, without the quotation marks) to be allowed.

**Comment by Gileba** [comment]
Version 3.4.1 is released and should fix this

**Comment by jobe001** [comment]
It’s perfect!

Thank you very much.

 

BR Johann

 

Von: Gijs Lamon ***@***.***> 
Gesendet: Samstag, 29. April 2023 10:33
An: Gileba-org/mod_tablemakerforcsv ***@***.***>
Cc: jobe001 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Gileba-org/mod_tablemakerforcsv] Links are not visible anymore (Issue #69)

 

Version 3.4.1 is released and should fix this
