### ISSUE TITLE
Rename module for listing on JED

### ISSUE THREAD

**Issue by Gileba** [Gileba-org/mod_tablemakerforcsv#89]
The JED requires a new name for this module to be published and acquire a new versioning system (= restarting from 1.0)

Any suggestions for a fancy name are welcome. 

Be aware that a new name will also require a new installation of the module and a remake of all instances of the module. I'll see what I can do to smoothen things out...

**Comment by AlainRnet** [comment]
CSV table maker ?

**Comment by AlainRnet** [comment]
Is there a way to contact Mostafa Shahiri and and asking him delete his module on the JED or become his module owner on the JED ?

**Comment by Gileba** [comment]
Contacted JED on how to proceed
