### ISSUE TITLE
Error: Invalid mime type

### ISSUE THREAD

**Issue by KHysiek** [Gileba-org/mod_tablemakerforcsv#90]
Hello,
I would like to use this extension but it doesn't work for me.
When configuring module from admin page it doesn't want to load my CSV file, giving error 
- when browsing from local side file : Invalid mime type on top of page as popup
- Select a CSV-file, This value is invalid : when selecting uploaded CSV file
- I have tried UTF-8, normal and MSDOS format options when exporting from excel but it won't help.
Cheers,
Krzysiek

**Comment by Gileba** [comment]
Hi Krzysiek

Sorry to here the extension isn't working for you.

Could you attach a demo file that returns the error so I can test it?

Kind regards
Gijs

**Comment by KHysiek** [comment]
Well, thats strange cause I can't attach file here on Github :( It gives me error below "Something went really wrong ..."

CSV is simple 

Pokoj;Nazwisko;Telefon
101;Ala Fasol;211
102;Kot Ali;315
103;Myszy Kota;431

**Comment by Gileba** [comment]
I'm afraid it has nothing to do with the module but with the file itself. Could you check if the attached file does the job?
[test.csv](https://github.com/Gileba-org/mod_tablemakerforcsv/files/11522752/test.csv)

**Comment by Gileba** [comment]
@KHysiek , can you have a look at my last reply?

**Comment by KHysiek** [comment]
I have looked but it doesnt work either. I have enabled CSV files in php and Joomla and don't have further ideas. I have moved to use another solution not involving CSV files. Thanks for reply though :)

**Comment by Gileba** [comment]
Closing this issue as it is not reproducable
