### ISSUE TITLE
General params layout shift

### ISSUE THREAD

**Issue by AlainRnet** [Gileba-org/mod_tablemakerforcsv#98]
The module edition is not displayed correctly at all: the fields usually on the right are displayed below and the menu assignment menu at the bottom, at the top depending on the tabs and the last tabs are all in sequence, independent of the clicked tab.

I looked at the XML file code but I don’t see the problem.

**Comment by Gileba** [comment]
Hi @AlainRnet 

I can confirm the bug. For some reason there's an <a>-tag added, which breaks the flex of the standard display.

Greetings
Gijs

**Comment by Gileba** [comment]
I'm building a release as I write :-)

**Comment by AlainRnet** [comment]
Yes!
Do you want I continue correcting other languages?

**Comment by Gileba** [comment]
No, they are all fixed in one single PR #99

**Comment by AlainRnet** [comment]
OK, I see. You should explain me how to do what I did in one shot ;-)
Good night.
